[package]
name = "wcstack"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive"] }
hex = "0.4.3"
prost = "0.12.6"
tempfile = "3.10.1"

[build-dependencies]
prost-build = "0.12.6"
